console.log(12 == "12")
console.log(12 === "12")
console.log(1 == true)
console.log(-1 == true)
console.log(1 === true)
console.log(0 == true)
console.log(0 === true)
console.log(null == 0)
console.log(undefined == 0)
console.log(undefined == null)
console.log(undefined === null)
console.log(!null)